#!/bin/sh
#SBATCH -p et2024
#SBATCH --mem-per-cpu=30G
#SBATCH -t 1-00:00:00
#SBATCH --array=0-29        # launch 20 jobs, 10 alphas per job
#SBATCH -n 1                # 1 task per job
pwd; hostname; date

~/Software/python_virtualenv/bin/python3.11 2cof_float3.py > 2cof_float3_interval500.out

date
