#!/bin/sh
#SBATCH -p et2024
#SBATCH --mem-per-cpu=30G
#SBATCH -t 01:00:00
#SBATCH -n 1                # 1 task per job
pwd; hostname; date

~/Software/python_virtualenv/bin/python3.11 2cof_float3_BayOpt.py > BayOpt_speed.out

date