#!/bin/sh
#SBATCH -p et2024
#SBATCH --mem-per-cpu=30G
#SBATCH -t 2:00
#SBATCH --array=0-29        # launch 30 jobs, 20-21 slope combos per job
#SBATCH -n 1                # 1 task per job
pwd; hostname; date

~/Software/python_virtualenv/bin/python3.11 Nfn1_varyH_bump.py > Nfn1_varyH_bump.out

date
