#!/bin/sh
#SBATCH -p et2024
#SBATCH --mem-per-cpu=30G
#SBATCH -t 5:00
#SBATCH --array=0-29        # launch 30 jobs
#SBATCH -n 1                # 1 task per job
pwd; hostname; date

~/Software/python_virtualenv/bin/python3.11 ramps-100.py > ramps-100.out

date
